[workspace]
authors = ["Jose Troche <jose.troche.coder@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "robot-voice-ai"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
