[workspace]
authors = ["Jose Troche <jose.troche.coder@gmail.com>"]
channels = ["conda-forge", "robostack-humble"]
name = "robot-voice-ai"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = {cmd = "colcon build --symlink-install", inputs = ["src"]}

[activation]
scripts = ["install/setup.bash"]

[activation.env]
RMW_IMPLEMENTATION = "rmw_fastrtps_cpp"
ROS_LOG_DIR = "/tmp/roslogs"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
numpy = ">=1.26,<3"
portaudio = ">=19.7.0,<20"

[pypi-dependencies]
av = "==14.0.0"
sounddevice = ">=0.5,<0.6"
faster-whisper = ">=1.1,<2"
